-- Snowflake export for /public/data/metrics_feedback.json
-- Source: gtmx_dashboard.ipynb cell 28 (Sterno + Offers feedback, chorus-enriched).
-- Prereq: scripts/snowflake_sync.py sheet pre-step populates:
--   TOAST.SOURCE_MANUAL.FROM_GOOGLE_SHEET_STERNO
--   TOAST.SOURCE_MANUAL.GOOGLE_SHEETS_OFFERS_FEEDBACK

WITH all_gtmx_chorus AS (
    SELECT
        acct.customer_name AS "account_name"
        , task.salesforce_accountid AS "salesforce_accountid"
        , task.comments AS "comments"
        , REGEXP_SUBSTR(task.comments, 'https://chorus\\.ai/meeting/[A-Za-z0-9]+')
            AS "chorus_link"
        , employee.full_name AS "rep_name"
        , COALESCE(task.completed_date, task.created_date)::DATE
            AS "chorus_date"
        , ROW_NUMBER() OVER (
            PARTITION BY task.salesforce_accountid
            ORDER BY COALESCE(task.completed_date, task.created_date) DESC
        ) AS "rn"
    FROM TOAST.ANALYTICS_CORE.TASK_ACTIVITY AS task
    INNER JOIN TOAST.ANALYTICS_CORE.EMPLOYEE_CURRENT AS employee
        ON task.task_ownerid = employee.salesforce_userid
    LEFT JOIN TOAST.ANALYTICS_CORE.ACCOUNT AS acct
        ON task.salesforce_accountid = acct.salesforce_accountid
    WHERE employee.manager_employee_id = '108763'
      AND task.type ILIKE '%Call%'
      AND task.status ILIKE '%completed%'
      AND task.subject ILIKE '%chorus%'
      AND task.comments IS NOT NULL
      AND task.comments != ''
      AND COALESCE(task.completed_date, task.created_date)::DATE > '2025-07-01'::DATE
    QUALIFY "rn" = 1
),
feedback_raw AS (
    SELECT
        TO_DATE(SPLIT_PART(COMPLETED_UPDATE_TIMESTAMP, ' ', 1), 'MM/DD/YYYY') AS feedback_date
        , ACCOUNT_OWNER AS rep_name
        , ACCOUNT_NAME AS account_name
        , 'Sterno' AS source
        , CONCAT_WS(CHR(10)
            , CASE WHEN OUTCOME != '' THEN 'Outcome: ' || OUTCOME END
            , CASE WHEN COMPETITOR != '' THEN ' | Competitor: ' || COMPETITOR END
            , CASE WHEN REASON_FOR_OUTCOME != '' THEN ' | Reason for Outcome: ' || REASON_FOR_OUTCOME END
            , CASE WHEN UPDATED_SUBSEGEMENT_DESCRIPTIONS_MAKE_SURE_TO_ADD_SUBSEGMENT_TO_SFDC_ACCOUNT_PROSPECTING_NOTES_FIELD != '' THEN ' | Updated Subsegment: ' || UPDATED_SUBSEGEMENT_DESCRIPTIONS_MAKE_SURE_TO_ADD_SUBSEGMENT_TO_SFDC_ACCOUNT_PROSPECTING_NOTES_FIELD END
            , CASE WHEN PRODUCT_MARKET_FIT_PRODUCT_ADVANTAGES != '' THEN ' | Product Market Fit / Product Advantages: ' || PRODUCT_MARKET_FIT_PRODUCT_ADVANTAGES END
            , CASE WHEN LOSS_REASON_PRODUCT_GAPS_IMPORTANT_FOR_LOSTDISQUALIFIED != '' THEN ' | Loss Reason: ' || LOSS_REASON_PRODUCT_GAPS_IMPORTANT_FOR_LOSTDISQUALIFIED END
            , CASE WHEN OPEN_COMMENTS != '' THEN ' | Open Comments: ' || OPEN_COMMENTS END
        ) AS feedback
    FROM TOAST.SOURCE_MANUAL.FROM_GOOGLE_SHEET_STERNO
    WHERE FEEDBACK_COMPLETED ILIKE 'TRUE'
      AND OUTCOME NOT ILIKE '%disqualified%'
      AND COMPLETED_UPDATE_TIMESTAMP IS NOT NULL
      AND COMPLETED_UPDATE_TIMESTAMP != ''

    UNION ALL

    SELECT
        TO_DATE(TIMESTAMP, 'MM/DD/YYYY HH24:MI:SS') AS feedback_date
        , INITCAP(REPLACE(SPLIT_PART(EMAIL_ADDRESS, '@', 1), '.', ' ')) AS rep_name
        , RESTAURANT_NAMES_ AS account_name
        , 'Offers' AS source
        , CONCAT_WS(CHR(10)
            , CASE WHEN WHAT_TYPE_OF_OFFER_WAS_USED_ IS NOT NULL THEN 'What type of offer was used: ' || WHAT_TYPE_OF_OFFER_WAS_USED_ END
            , CASE WHEN HOW_DID_THE_CX_RATE_THE_OFFER_PERFORMANCE_ IS NOT NULL THEN ' | How did the CX rate the offer performance: ' || HOW_DID_THE_CX_RATE_THE_OFFER_PERFORMANCE_ END
            , CASE WHEN CX_NET_SALES_FROM_OFFER IS NOT NULL THEN ' | CX net sales from offer: ' || CX_NET_SALES_FROM_OFFER END
            , CASE WHEN WHAT_WAS_THE_CXS_MAIN_GOAL_FROM_USING_OFFERS_TELL_ME_ABOUT_YOUR_MAIN_GOALS_WITH_RUNNING_OFFERS IS NOT NULL THEN ' | Main goal from using offers: ' || WHAT_WAS_THE_CXS_MAIN_GOAL_FROM_USING_OFFERS_TELL_ME_ABOUT_YOUR_MAIN_GOALS_WITH_RUNNING_OFFERS END
            , CASE WHEN WHAT_FEATURES_WOULD_CUSTOMERS_LIKE_TO_SEE_IN_OFFERS_BASED_ON_WHAT_YOU_HAVE_SEEN_WHAT_IS_THE_OFFERS_PRODUCT_MISSING_IS_THERE_ANYTHING_YOU_WISH_IT_COULD_DO IS NOT NULL THEN ' | Features customers would like: ' || WHAT_FEATURES_WOULD_CUSTOMERS_LIKE_TO_SEE_IN_OFFERS_BASED_ON_WHAT_YOU_HAVE_SEEN_WHAT_IS_THE_OFFERS_PRODUCT_MISSING_IS_THERE_ANYTHING_YOU_WISH_IT_COULD_DO END
            , CASE WHEN HOW_WOULD_YOU_LIKE_TO_SEE_OFFERS_DISTRIBUTED_WHAT_CHANNELS_WEB_SMS_APP_ETC_DO_YOU_CURRENTLY_HAVE_A_PLAN_ON_HOW_YOUR_MARKET_THESE_OFFERS_HOW_WOULD_YOU_WANT_TOAST_TO_HELP_WITH_THAT IS NOT NULL THEN ' | How to distribute offers: ' || HOW_WOULD_YOU_LIKE_TO_SEE_OFFERS_DISTRIBUTED_WHAT_CHANNELS_WEB_SMS_APP_ETC_DO_YOU_CURRENTLY_HAVE_A_PLAN_ON_HOW_YOUR_MARKET_THESE_OFFERS_HOW_WOULD_YOU_WANT_TOAST_TO_HELP_WITH_THAT END
            , CASE WHEN WHAT_IS_THE_MAIN_FEEDBACK_CUSTOMER_GAVE_ON_HOW_TO_IMPROVE_OFFERSWHAT_TO_KEEP_IN_MIND_AS_WE_CONTINUE_TO_DEVELOP_OFFERS_ IS NOT NULL THEN ' | Main feedback to improve offers: ' || WHAT_IS_THE_MAIN_FEEDBACK_CUSTOMER_GAVE_ON_HOW_TO_IMPROVE_OFFERSWHAT_TO_KEEP_IN_MIND_AS_WE_CONTINUE_TO_DEVELOP_OFFERS_ END
            , CASE WHEN IN_THE_FUTURE_HOW_WOULD_YOU_LIKE_OFFERS_RAN_AT_YOUR_RESTAURANT_THIS_MIGHT_BE_A_QUESTION_YOU_ASK_OR_SOMETHING_YOU_GAUGE_FROM_THE_CONVERSATIO IS NOT NULL THEN ' | Future offers preference: ' || IN_THE_FUTURE_HOW_WOULD_YOU_LIKE_OFFERS_RAN_AT_YOUR_RESTAURANT_THIS_MIGHT_BE_A_QUESTION_YOU_ASK_OR_SOMETHING_YOU_GAUGE_FROM_THE_CONVERSATIO END
            , CASE WHEN DOES_THEIR_RESTAURANT_USE_THE_TOAST_LOCAL_APP_HAVE_YOU_EVER_USED_THE_TOAST_LOCAL_APP_BEFORE IS NOT NULL THEN ' | Uses Toast Local App: ' || DOES_THEIR_RESTAURANT_USE_THE_TOAST_LOCAL_APP_HAVE_YOU_EVER_USED_THE_TOAST_LOCAL_APP_BEFORE END
            , CASE WHEN IS_THIS_RESTAURANT_EXCITED_ABOUT_THE_APP_WHAT_DO_YOU_LIKE_ABOUT_THE_APP_ IS NOT NULL THEN ' | Excited about the app: ' || IS_THIS_RESTAURANT_EXCITED_ABOUT_THE_APP_WHAT_DO_YOU_LIKE_ABOUT_THE_APP_ END
            , CASE WHEN WHAT_WOULD_BE_A_MOTIVATOR_TO_GET_GUESTS_TO_DOWNLOAD_THE_APP IS NOT NULL THEN ' | Motivator to download: ' || WHAT_WOULD_BE_A_MOTIVATOR_TO_GET_GUESTS_TO_DOWNLOAD_THE_APP END
            , CASE WHEN AS_A_RESTAURANT_OWNER_WHAT_WOULD_LIKE_US_BUILD_INTO_THE_APP_WHAT_WOULD_HELP_YOU_IN_REACHING_YOUR_GOALS IS NOT NULL THEN ' | What to build into the app: ' || AS_A_RESTAURANT_OWNER_WHAT_WOULD_LIKE_US_BUILD_INTO_THE_APP_WHAT_WOULD_HELP_YOU_IN_REACHING_YOUR_GOALS END
            , CASE WHEN DOES_THE_PROCESS_OF_CREATING_FEEL_INTUITIVE_ IS NOT NULL THEN ' | Process feel intuitive: ' || DOES_THE_PROCESS_OF_CREATING_FEEL_INTUITIVE_ END
            , CASE WHEN WHERE_IN_TOASTWEB_SHOULD_OFFERS_LIVE_WHEN_YOU_ARE_IN_YOUR_BACKEND_WHERE_WOULD_IT_MAKE_THE_MOST_TO_PLACE_OFFERS_HOW_DO_YOU_NORMALLY_DISCOVER_THINGS_IN_TOAST_WEB IS NOT NULL THEN ' | Where should offers live in ToastWeb: ' || WHERE_IN_TOASTWEB_SHOULD_OFFERS_LIVE_WHEN_YOU_ARE_IN_YOUR_BACKEND_WHERE_WOULD_IT_MAKE_THE_MOST_TO_PLACE_OFFERS_HOW_DO_YOU_NORMALLY_DISCOVER_THINGS_IN_TOAST_WEB END
            , CASE WHEN REPORTING_FEATURES_IF_YOU_COULD_WAIVE_A_MAGIC_WAND_WHAT_TYPE_OF_REPORTINGDATA_DO_YOU_WANT_TO_SEE_ON_OFFERS IS NOT NULL THEN ' | Reporting features: ' || REPORTING_FEATURES_IF_YOU_COULD_WAIVE_A_MAGIC_WAND_WHAT_TYPE_OF_REPORTINGDATA_DO_YOU_WANT_TO_SEE_ON_OFFERS END
            , CASE WHEN CHORUS_CALL_LINK IS NOT NULL THEN ' | Chorus call link: ' || CHORUS_CALL_LINK END
            , CASE WHEN NOTES_LINK_SHARE_WITH_ALL_OF_TOAST IS NOT NULL THEN ' | Notes link: ' || NOTES_LINK_SHARE_WITH_ALL_OF_TOAST END
        ) AS feedback
    FROM TOAST.SOURCE_MANUAL.GOOGLE_SHEETS_OFFERS_FEEDBACK
    WHERE TIMESTAMP IS NOT NULL
      AND TIMESTAMP != ''
      AND TIMESTAMP NOT ILIKE 'Timestamp'
)
SELECT
    MD5(CONCAT_WS('|', feedback_raw.feedback_date, feedback_raw.rep_name, feedback_raw.account_name, feedback_raw.source)) AS id
    , feedback_raw.feedback_date
    , CASE
        WHEN feedback_raw.rep_name IS NULL OR feedback_raw.rep_name = '' THEN
            CASE feedback_raw.source
                WHEN 'Sterno' THEN 'Ross Armstrong'
                WHEN 'Mad Max' THEN 'Zoe Lang'
                WHEN 'Guest Pro' THEN 'Lo Picton'
            END
        ELSE feedback_raw.rep_name
      END AS rep_name
    , feedback_raw.account_name
    , feedback_raw.source
    , feedback_raw.feedback
FROM feedback_raw
ORDER BY feedback_raw.feedback_date DESC;
